### ISSUE TITLE
several shields are links to broken symbolic links

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/mapbox-studio-osm-bright.tm2#19]
From [this commit](https://github.com/mapbox/mapbox-studio-osm-bright.tm2/commit/4061e6a6c672dbc97ed95d0acf18277dfcafb101), there were several shields added to the repo that consist of symbolic links to aj's files ;p

**Comment by ajashton** [comment]
Wherps, sorry. Fixed here and in a few other projects. Fortunately npm dereferences links during package creation so the published modules are fine.

(I opted to replace the links with full copies rather than just fix the references since the presence of symlinks was already causing a bit of confusion for a couple people.)
